name: CI/CD - Tests & Coverage

on:
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x  # Adjust based on your project

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./VoxelMeshOptimizerLibrary

      - name: Run tests with coverage
        run: |
          dotnet test tests/VoxelMeshOptimizer.Tests.csproj \
            --configuration Release \
            --collect:"XPlat Code Coverage" \
            --logger trx \
            --results-directory ./TestResults
        working-directory: ./VoxelMeshOptimizerLibrary

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: VoxelMeshOptimizerLibrary/TestResults

      - name: Generate coverage report
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          reportgenerator -reports:TestResults/*/coverage.cobertura.xml \
            -targetdir:TestResults/CoverageReport \
            -reporttypes:Html
        working-directory: ./VoxelMeshOptimizerLibrary

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: VoxelMeshOptimizerLibrary/TestResults/CoverageReport
  benchmark:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./VoxelMeshOptimizerLibrary

      - name: Run benchmarks
        run: dotnet run --project examples/Benchmark/Benchmark.csproj -c Release -- --exporters json
        working-directory: ./VoxelMeshOptimizerLibrary

      - name: Verify benchmark thresholds
        env:
          BENCHMARK_THRESHOLDS: examples/Benchmark/benchmark_thresholds.json
        run: python scripts/verify_benchmarks.py BenchmarkDotNet.Artifacts/results/SpeedBenchmarks-report.json
        working-directory: ./VoxelMeshOptimizerLibrary

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: VoxelMeshOptimizerLibrary/BenchmarkDotNet.Artifacts
